name: abirpyenv
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py37_0
  - _r-mutex=1.0.1=anacondar_1
  - absl-py=0.10.0=py37hc8dfbb8_0
  - affine=2.3.0=py_0
  - alabaster=0.7.12=py37_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py37_0
  - anaconda-project=0.8.4=py_0
  - argh=0.26.2=py37_0
  - arrow=0.15.5=py37_0
  - asn1crypto=1.2.0=py37_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astroid=2.3.3=py37_0
  - astropy=3.2.3=py37he774522_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py37_0
  - backports.shutil_get_terminal_size=1.0.0=py37_2
  - bcrypt=3.1.7=py37he774522_0
  - beautifulsoup4=4.8.1=py37_0
  - binaryornot=0.4.4=py_1
  - bitarray=1.1.0=py37he774522_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - blosc=1.16.3=h7bd577a_0
  - boto=2.49.0=py37_0
  - boto3=1.16.33=pyhd8ed1ab_0
  - botocore=1.19.33=pyhd8ed1ab_0
  - bottleneck=1.3.1=py37h8c2d366_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.12.5=h5b45459_0
  - cartopy=0.17.0=py37hde43876_1009
  - certifi=2020.12.5=py37h03978a9_1
  - cffi=1.13.2=py37h7a1dbc1_0
  - cfitsio=3.470=he774522_2
  - cftime=1.4.1=py37hda49f71_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py37_0
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py37_1
  - colorcet=2.0.6=py_0
  - comtypes=1.1.7=py37_0
  - conda=4.10.1=py37h03978a9_0
  - conda-build=3.18.11=py37_0
  - conda-package-handling=1.6.0=py37h2fa13f4_1
  - console_shortcut=0.1.1=3
  - contextlib2=0.6.0.post1=py_0
  - cookiecutter=1.7.0=py_0
  - coverage=4.5.4=py37hfa6e2cd_0
  - cryptography=2.8=py37h7a1dbc1_0
  - curl=7.67.0=h2a8f88b_0
  - cycler=0.10.0=py37_0
  - cython=0.29.14=py37ha925a31_0
  - cytoolz=0.10.1=py37he774522_0
  - dask=2.9.0=py_0
  - dask-core=2.9.0=py_0
  - datashader=0.12.1=py_0
  - datashape=0.5.4=py_1
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - deprecated=1.2.7=py_0
  - descartes=1.1.0=py_4
  - diff-match-patch=20181111=py_0
  - distributed=2.9.0=py_0
  - docopt=0.6.2=py_1
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.5=he025d50_0
  - fastcache=1.1.0=py37he774522_0
  - filelock=3.0.12=py_0
  - fiona=1.8.11=py37h737a305_0
  - firefox=78.0esr=ha925a31_0
  - flake8=3.7.9=py37_0
  - flask=1.1.1=py_0
  - folium=0.10.1=py_0
  - freetype=2.9.1=ha9979f8_1
  - freexl=1.0.5=hfa6e2cd_0
  - fsspec=0.6.0=py_0
  - future=0.18.2=py37_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gdal=3.0.2=py37hdf43c64_0
  - geckodriver=0.26.0=he025d50_0
  - geographiclib=1.50=py_0
  - geopandas=0.9.0=pyhd8ed1ab_0
  - geopy=1.20.0=py_0
  - georasters=0.5.15=py_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.5.1=h5770a2b_0
  - geoviews=1.9.1=py_0
  - geoviews-core=1.9.1=py_0
  - get_terminal_size=1.0.0=h38e98db_0
  - gevent=1.4.0=py37he774522_0
  - glob2=0.7=py_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - greenlet=0.4.15=py37hfa6e2cd_0
  - grpcio=1.31.0=py37h554427f_0
  - h5py=2.9.0=py37h5e291fa_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py37_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - imagesize=1.1.0=py37_0
  - importlib_metadata=1.1.0=py37_0
  - intel-openmp=2019.4=245
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.10.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jdcal=1.4.1=py_0
  - jedi=0.14.1=py37_0
  - jenkspy=0.1.4=py37hfa6e2cd_1000
  - jinja2=2.10.3=py_0
  - jinja2-time=0.2.0=py_2
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.14.0=py_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.3=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - kealib=1.4.7=h07cbb95_6
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - keyring=19.2.0=py37_0
  - kiwisolver=1.1.0=py37ha925a31_0
  - krb5=1.16.1=hc04afaa_7
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libarchive=3.3.3=h0643e63_5
  - libblas=3.8.0=14_mkl
  - libboost=1.67.0=hd9e427e_4
  - libcurl=7.67.0=h2a8f88b_0
  - libgdal=3.0.2=h1155b67_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - liblapack=3.8.0=14_mkl
  - liblief=0.9.0=ha925a31_2
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libprotobuf=3.13.0=h200bbdf_0
  - libsodium=1.0.16=h9d3ae62_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.9=h464c3ec_0
  - libxslt=1.1.33=h579f668_0
  - llvmlite=0.30.0=py37ha925a31_0
  - locket=0.2.0=py37_1
  - lxml=4.4.2=py37h1350720_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - m2w64-bwidget=1.9.10=2
  - m2w64-bzip2=1.0.6=6
  - m2w64-expat=2.1.1=2
  - m2w64-fftw=3.3.4=6
  - m2w64-flac=1.3.1=3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-gsl=2.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libjpeg-turbo=1.4.2=3
  - m2w64-libogg=1.3.2=3
  - m2w64-libpng=1.6.21=2
  - m2w64-libsndfile=1.0.26=2
  - m2w64-libtiff=4.0.6=2
  - m2w64-libvorbis=1.3.5=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-libxml2=2.9.3=4
  - m2w64-mpfr=3.1.4=4
  - m2w64-pcre=8.38=2
  - m2w64-speex=1.2rc2=3
  - m2w64-speexdsp=1.2rc3=3
  - m2w64-tcl=8.6.5=3
  - m2w64-tk=8.6.5=3
  - m2w64-tktable=2.10=5
  - m2w64-wineditline=2.101=5
  - m2w64-xz=5.2.2=2
  - m2w64-zlib=1.2.8=10
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.1=py37hc8f65d3_0
  - matplotlib-base=3.1.2=py37h2981e6d_1
  - mccabe=0.6.1=py37_1
  - menuinst=1.4.16=py37he774522_0
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - mock=3.0.5=py37_0
  - more-itertools=7.2.0=py37_0
  - mpmath=1.1.0=py37_0
  - msgpack-python=0.6.1=py37h74a9793_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py37_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - netcdf4=1.4.2=py37h812ae01_0
  - networkx=2.4=py_0
  - nltk=3.4.5=py37_0
  - nose=1.3.7=py37_2
  - notebook=6.0.2=py37_0
  - numba=0.46.0=py37hf9181ef_0
  - numexpr=2.7.0=py37hdce8814_0
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=h5ec785f_1
  - openpyxl=3.0.2=py_0
  - openssl=1.1.1k=h8ffe710_0
  - osmnet=0.1.5=py_3
  - osmnx=0.11=py_0
  - owslib=0.23.0=pyhd8ed1ab_0
  - packaging=19.2=py_0
  - palettable=3.3.0=py_0
  - pandana=0.4.4=py37he350917_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - paramiko=2.6.0=py37_0
  - parso=0.5.1=py_0
  - partd=1.1.0=py_0
  - path.py=12.0.2=py_0
  - pathlib2=2.3.5=py37_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py37_0
  - pcre=8.43=ha925a31_0
  - pep8=1.7.1=py37_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pkginfo=1.5.0.1=py37_0
  - pluggy=0.13.1=py37_0
  - ply=3.11=py37_0
  - postgresql=11.2=h3235a2c_0
  - powershell_shortcut=0.0.1=2
  - poyo=0.5.0=py_0
  - proj=6.2.1=h9f7ef89_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - protobuf=3.13.0=py37h1834ac0_0
  - psutil=5.6.7=py37he774522_0
  - py=1.8.0=py37_0
  - py-lief=0.9.0=py37ha925a31_2
  - pycodestyle=2.5.0=py37_0
  - pycosat=0.6.3=py37hfa6e2cd_0
  - pycparser=2.19=py37_0
  - pycrypto=2.6.1=py37hfa6e2cd_9
  - pyct-core=0.4.8=py_0
  - pycurl=7.43.0.3=py37h7a1dbc1_0
  - pydocstyle=4.0.1=py_0
  - pyepsg=0.4.0=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.5.2=py_0
  - pykdtree=1.3.4=py37hda49f71_0
  - pylint=2.4.4=py37_0
  - pympler=0.7=py_0
  - pynacl=1.3.0=py37h62dcd97_0
  - pyodbc=4.0.27=py37ha925a31_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyproj=2.4.1=py37hc6484ec_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.15.6=py37he774522_0
  - pysal=2.1.0=py_0
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py37_0
  - pytables=3.6.1=py37h1da0976_0
  - pytest=5.3.1=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.6.0=py_0
  - pytest-astropy-header=0.1.1=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.2=py_0
  - python-language-server=0.31.2=py37_0
  - python-libarchive-c=2.8=py37_13
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.6=py_0
  - pywavelets=1.1.1=py37he774522_0
  - pywin32=223=py37hfa6e2cd_1
  - pywin32-ctypes=0.2.0=py37_0
  - pywinpty=0.5.5=py37_1000
  - pyyaml=5.1.2=py37he774522_0
  - pyzmq=18.1.0=py37ha925a31_0
  - qdarkstyle=2.7=py_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.6.0=py_0
  - qtconsole=4.6.0=py_0
  - qtpy=1.9.0=py_0
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.1.8=r36hda5aaf8_0
  - r-base=3.6.3=hf0ea6f9_2
  - r-bit=1.1_15.2=r36hda5aaf8_1
  - r-bit64=0.9_7=r36hda5aaf8_1002
  - r-blob=1.2.1=r36h6115d3f_1
  - r-cli=2.0.2=r36h6115d3f_1
  - r-crayon=1.3.4=r36h6115d3f_1003
  - r-dbi=1.1.0=r36h6115d3f_1
  - r-dbplyr=1.4.4=r36h6115d3f_0
  - r-digest=0.6.25=r36h796a38f_2
  - r-dplyr=1.0.0=r36h796a38f_0
  - r-ellipsis=0.3.1=r36hda5aaf8_0
  - r-fansi=0.4.1=r36hda5aaf8_1
  - r-generics=0.0.2=r36h6115d3f_1003
  - r-glue=1.4.1=r36hda5aaf8_0
  - r-lifecycle=0.2.0=r36h6115d3f_1
  - r-magrittr=1.5=r36h6115d3f_1003
  - r-memoise=1.1.0=r36h6115d3f_1004
  - r-pillar=1.4.6=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-plogr=0.2.0=r36h6115d3f_1003
  - r-purrr=0.3.4=r36hda5aaf8_1
  - r-r6=2.4.1=r36h6115d3f_1
  - r-rcpp=1.0.5=r36h796a38f_0
  - r-rlang=0.4.7=r36hda5aaf8_0
  - r-rsqlite=2.2.0=r36h796a38f_2
  - r-tibble=3.0.3=r36hda5aaf8_0
  - r-tidyselect=1.1.0=r36h6115d3f_0
  - r-utf8=1.1.4=r36hda5aaf8_1003
  - r-vctrs=0.3.2=r36hda5aaf8_0
  - r-zeallot=0.1.0=r36h6115d3f_1002
  - rasterio=1.1.1=py37h2617b1b_0
  - rasterstats=0.13.1=py_1
  - requests=2.22.0=py37_1
  - ripgrep=11.0.2=h301d43c_3
  - rope=0.14.0=py_0
  - rtree=0.8.3=py37_0
  - ruamel_yaml=0.15.46=py37hfa6e2cd_0
  - s3transfer=0.3.3=py_3
  - scikit-image=0.15.0=py37ha925a31_0
  - scikit-learn=0.21.3=py37h6288b17_0
  - scipy=1.3.2=py37h29ff71c_0
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py37_0
  - setuptools=42.0.2=py37_0
  - shapely=1.6.4=py37hd830579_0
  - simplegeneric=0.8.1=py37_2
  - simplejson=3.17.0=py37hfa6e2cd_0
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - snappy=1.1.7=h777316e_3
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - sortedcollections=1.1.2=py37_0
  - sortedcontainers=2.1.0=py37_0
  - soupsieve=1.9.5=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=4.0.0=py37_0
  - spyder-kernels=1.8.1=py37_0
  - sqlalchemy=1.3.11=py37he774522_0
  - sqlite=3.30.1=he774522_0
  - statsmodels=0.10.1=py37h8c2d366_0
  - sympy=1.4=py37_0
  - tbb=2018.0.5=he980bc4_0
  - tblib=1.5.0=py_0
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=h1f41ff6_0
  - tensorflow-base=1.14.0=py37hc8dfbb8_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tiledb=1.6.3=h7b000aa_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37he774522_0
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.3=py_0
  - ujson=1.35=py37hfa6e2cd_0
  - unicodecsv=0.14.1=py37_0
  - urbanaccess=0.2.0=py_0
  - urllib3=1.25.7=py37_0
  - vc=14.1=h0510ff6_4
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - watchdog=0.9.0=py37_1
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - whichcraft=0.6.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - win_unicode_console=0.5=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37he774522_0
  - xerces-c=3.2.2=ha925a31_0
  - xlrd=1.2.0=py37_0
  - xlsxwriter=1.2.6=py_0
  - xlwings=0.16.1=py37_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=h33f27b4_3
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - aenum==2.2.6
    - aiohttp==3.6.2
    - alpha-vantage==2.2.0
    - appdirs==1.4.4
    - async-timeout==3.0.1
    - biom-format==2.1.10
    - bokeh==2.1.1
    - centerline==0.6.3
    - colorama==0.4.4
    - colorlover==0.3.0
    - contextily==1.0.0
    - cufflinks==0.17.3
    - emcee==3.0.2
    - filetype==1.0.7
    - fpdf==1.7.2
    - furo==2021.8.31
    - geodesign==0.26
    - geoshapes==0.0.4
    - geosolution==0.64
    - gstools==1.2.1
    - h3==3.7.3
    - hankel==1.1.0
    - holoviews==1.13.3
    - hvplot==0.7.1
    - importlib-metadata==4.8.1
    - keplergl==0.2.2
    - libpysal==4.3.0
    - mapclassify==2.3.0
    - mercantile==1.1.5
    - meshio==4.0.16
    - momepy==0.3.0
    - multidict==4.7.6
    - nptdms==1.0.0
    - numpy==1.17.4
    - oauthlib==3.1.0
    - pandas==1.0.5
    - panel==0.9.7
    - param==1.9.3
    - pathlib==1.0.1
    - perspective-python==0.10.2
    - pillow==6.2.1
    - plotly==4.9.0
    - pooch==1.1.1
    - probscale==0.2.3
    - psycopg2==2.8.6
    - public==2019.4.13
    - pyct==0.4.6
    - pyevtk==1.1.1
    - pykrige==1.5.0
    - pyperclip==1.8.0
    - pysimplegui==4.34.0
    - pysimpleguiweb==0.39.0
    - pyvista==0.25.3
    - pyviz-comms==0.7.6
    - quantile==0.0.1
    - readme-renderer==30.0
    - remi==2020.3.10
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - rfc3986==1.5.0
    - rpy2==3.3.5
    - scikit-gstat==0.2.7
    - scooby==0.5.5
    - selenium==3.141.0
    - sentinelhub==3.1.0
    - spasis==0.5
    - sphinx==4.1.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-serializinghtml==1.1.5
    - temp==2020.4.16
    - tifffile==2020.12.8
    - tkdatacanvas==0.1.1
    - tqdm==4.62.2
    - traittypes==0.2.1
    - twine==3.4.2
    - typing-extensions==3.7.4.2
    - tzlocal==2.1
    - utm==0.7.0
    - verde==1.5.0
    - vtk==9.0.1
    - xarray==0.15.1
    - yarl==1.4.2
    - yellowbrick==1.1
prefix: C:\Users\ABIR RAIHAN\.conda\envs\abirpyenv
